package main.java.com.charbuilder.utils;

public enum Weapons {
    SIMPLE_WEAPONS, HAND_CROSSBOWS, LONGSWORDS, SHORTSWORDS, MARTIAL_WEAPONS, GREATAXE, MARTIAL_MELEE_WEAPON, JAVELIN, RAPIER, MACE, WARHAMMER;
}
